{
	"version": 1688367109,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bum-sheet0.png",
		"images/bg.png",
		"images/shadow-sheet0.png",
		"images/shadow-sheet1.png",
		"images/blurboy-sheet0.png",
		"images/eye-sheet0.png",
		"images/letterb-sheet0.png",
		"images/letter-sheet0.png",
		"images/blur-sheet0.png",
		"images/blur-sheet1.png",
		"images/circle-sheet0.png",
		"images/circle-sheet1.png",
		"images/circle-sheet2.png",
		"images/tiledbackground.png",
		"images/asset3-sheet0.png",
		"images/asset3-sheet1.png",
		"images/boardfinal-sheet0.png",
		"images/hand-sheet0.png",
		"images/sprite-sheet0.png",
		"images/particles.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/welldone.m4a",
		"media/welldone.ogg",
		"media/sao dung.m4a",
		"media/sao dung.ogg",
		"media/check dung.m4a",
		"media/check dung.ogg",
		"media/wrong.m4a",
		"media/wrong.ogg",
		"media/music.m4a",
		"media/music.ogg",
		"media/ping.m4a",
		"media/ping.ogg",
		"media/blooper 2.m4a",
		"media/blooper 2.ogg",
		"media/b.m4a",
		"media/b.ogg",
		"media/boy.m4a",
		"media/boy.ogg",
		"media/bb.m4a",
		"media/bb.ogg",
		"media/a.m4a",
		"media/a.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}