{
	"version": 1688367361,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/nen-sheet0.png",
		"images/antl-sheet0.png",
		"images/antl-sheet1.png",
		"images/co-sheet0.png",
		"images/aa-sheet0.png",
		"images/antr-sheet0.png",
		"images/antr-sheet1.png",
		"images/blue-sheet0.png",
		"images/blue-sheet1.png",
		"images/cyan-sheet0.png",
		"images/cyan-sheet1.png",
		"images/yellow-sheet0.png",
		"images/yellow-sheet1.png",
		"images/purple-sheet0.png",
		"images/purple-sheet1.png",
		"images/pink-sheet0.png",
		"images/pink-sheet1.png",
		"images/green-sheet0.png",
		"images/green-sheet1.png",
		"images/red-sheet0.png",
		"images/orange-sheet0.png",
		"images/orange-sheet1.png",
		"images/point-sheet0.png",
		"images/boss-sheet0.png",
		"images/cursor-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/effectclick-sheet0.png",
		"images/particles3.png",
		"images/sangchu-sheet0.png",
		"images/ant-sheet0.png",
		"images/kien-sheet0.png",
		"images/sanga-sheet0.png",
		"images/particlesmic.png",
		"images/sprite3-sheet0.png",
		"images/sangsao-sheet0.png",
		"images/hole-sheet0.png",
		"images/sprite-sheet0.png",
		"images/tick-sheet0.png",
		"images/sangant-sheet0.png",
		"images/sangant2-sheet0.png",
		"media/a.m4a",
		"media/a.ogg",
		"media/aa.m4a",
		"media/aa.ogg",
		"media/ant.m4a",
		"media/ant.ogg",
		"media/fx- well done.m4a",
		"media/fx- well done.ogg",
		"media/dung 2.m4a",
		"media/dung 2.ogg",
		"media/a a ant.m4a",
		"media/a a ant.ogg",
		"media/dung.m4a",
		"media/dung.ogg",
		"media/star ding.m4a",
		"media/star ding.ogg",
		"media/blooper 4.m4a",
		"media/blooper 4.ogg",
		"media/pop up.m4a",
		"media/pop up.ogg",
		"media/2019-10-21_-_feels_good_-_david_fesliyan.m4a",
		"media/2019-10-21_-_feels_good_-_david_fesliyan.ogg",
		"media/nhac well done 1.m4a",
		"media/nhac well done 1.ogg",
		"media/2019-04-07_-_curious_tip_toe_-_www.fesliyanstudios.com.m4a",
		"media/2019-04-07_-_curious_tip_toe_-_www.fesliyanstudios.com.ogg",
		"media/marchdsdsdsdsdsdsdsdsdsdsdsd.m4a",
		"media/marchdsdsdsdsdsdsdsdsdsdsdsd.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}