{
	"version": 1766643985,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/nenstart-sheet0.png",
		"images/bg0-sheet0.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/item-sheet2.png",
		"images/img_wrong-sheet0.png",
		"images/img_dau-sheet0.png",
		"images/img_cuoi-sheet0.png",
		"images/bangchu-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/lop1.png",
		"images/lop2.png",
		"images/lop3.png",
		"images/particles.png",
		"images/tuong-sheet0.png",
		"images/check-sheet0.png",
		"images/micro-sheet0.png",
		"images/micro-sheet1.png",
		"images/sprite12-sheet0.png",
		"images/mancuoi-sheet0.png",
		"images/sau-sheet0.png",
		"images/chieusao-sheet0.png",
		"images/canvas.png",
		"images/particles2.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/xoalop2-sheet0.png",
		"images/xoalop3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/handclick-sheet0.png",
		"images/co-sheet0.png",
		"images/co-sheet1.png",
		"images/hatsao-sheet0.png",
		"images/hatsao-sheet1.png",
		"images/hatsao-sheet2.png",
		"images/nen_demo.png",
		"images/sprite5-sheet0.png",
		"images/particles3.png",
		"media/start game.m4a",
		"media/start game.ogg",
		"media/xuat hien bang.m4a",
		"media/xuat hien bang.ogg",
		"media/ding 1.m4a",
		"media/ding 1.ogg",
		"media/wrong.m4a",
		"media/wrong.ogg",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/fantastic tone boy.m4a",
		"media/fantastic tone boy.ogg",
		"media/well done end game.m4a",
		"media/well done end game.ogg",
		"media/nhacnen.m4a",
		"media/nhacnen.ogg",
		"media/ant.m4a",
		"media/boy.m4a",
		"media/ant.ogg",
		"media/boy.ogg",
		"media/checkdung.m4a",
		"media/checkdung.ogg",
		"media/checksai.m4a",
		"media/checksai.ogg",
		"media/dung.m4a",
		"media/dung.ogg",
		"media/try again.m4a",
		"media/try again.ogg",
		"media/dao.m4a",
		"media/dao.ogg",
		"media/xuc.m4a",
		"media/xuc.ogg",
		"media/show micro.m4a",
		"media/show micro.ogg",
		"media/ding 2.m4a",
		"media/ding 2.ogg",
		"media/sound_dao.m4a",
		"media/sound_dao.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"zlib_and_gzip.min.js"
	]
}