{
	"version": 1688367343,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/bg-sheet1.png",
		"images/particles.png",
		"images/particles2.png",
		"images/particles3.png",
		"images/boss-sheet0.png",
		"images/boss-sheet1.png",
		"images/boss-sheet2.png",
		"images/sprite-sheet0.png",
		"images/anhsang-sheet0.png",
		"images/anhsang-sheet1.png",
		"images/kienxanh-sheet0.png",
		"images/kiencam-sheet0.png",
		"images/kiencam-sheet1.png",
		"images/kiendo-sheet0.png",
		"images/kiendo-sheet1.png",
		"images/kienxanhla-sheet0.png",
		"images/kienhong-sheet0.png",
		"images/kienhong-sheet1.png",
		"images/kientim-sheet0.png",
		"images/kientim-sheet1.png",
		"images/kienvang-sheet0.png",
		"images/kienxanhbien-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/handclick-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/hat-sheet0.png",
		"images/hat-sheet1.png",
		"images/particles4.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/audio.m4a",
		"media/audio.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/a.m4a",
		"media/a.ogg",
		"media/hatbay.m4a",
		"media/hatbay.ogg",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/thua.m4a",
		"media/thua.ogg",
		"media/ketthuc.m4a",
		"media/ketthuc.ogg",
		"media/well done end game.m4a",
		"media/well done end game.ogg",
		"media/welldone.m4a",
		"media/welldone.ogg",
		"media/buocchan.m4a",
		"media/buocchan.ogg",
		"media/nhacnen.m4a",
		"media/nhacnen.ogg",
		"media/rap vo cho trong.m4a",
		"media/rap vo cho trong.ogg",
		"media/2.m4a",
		"media/2.ogg",
		"media/ding 2.m4a",
		"media/ding 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}